baseURL:  'http://localhost:1313/'
languageCode: 'en-gb'

enableRobotsTXT: true

params:
  title: 'Carroll Family Archive'
  description: ""

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
